extends:
  - standard
  - plugin:unicorn/recommended
  - prettier
  - prettier/standard

parserOptions:
  ecmaVersion: 2020
  sourceType: module

plugins:
  - prettier
  - standard
  - unicorn

rules:
    "prettier/prettier": "error"
    "unicorn/prevent-abbreviations": "off"
