parser: babel-eslint
extends:
  - semistandard
  - plugin:unicorn/recommended
  - prettier/standard
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 2020
  sourceType: module

plugins:
  - prettier
  - standard
  - unicorn

rules:
    prettier/prettier: error
    unicorn/consistent-function-scoping: off
    unicorn/explicit-length-check: off
    unicorn/prevent-abbreviations: off
