printWidth: 80
endOfLine: lf
useTabs: false
tabWidth: 4

semi: true
arrowParens: always
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
jsxBracketSameLine: false

quoteProps: as-needed
trailingComma: es5

htmlWhitespaceSensitivity: css
proseWrap: always
