import {squashObjs} from '../src/utils.js'
const objectify = (list) => squashObjs(
    list.map((item) => ({[item]: item}))
)

// Server list thanks to https://github.com/thisnameissoclever/sn-js-lib
const serverGlobalList = [
    'ac',
    'ac_derived_field_support',
    'ActionSecurity',
    'AjaxCompleter',
    'AjaxEmailClientCompleter',
    'AjaxOtherCompleter',
    'AjaxReferenceChoice',
    'AjaxReferenceCompleter',
    'AJAXReferenceControls',
    'AjaxTableCompleter',
    'AttachmentUploader',
    'AutoComplete',
    'calendar',
    'Catalog',
    'Class',
    'condition',
    'context_actions',
    'CookieJar',
    'CurrencyFormat',
    'current',
    'CustomEventManager',
    'depends',
    'DerivedFields',
    'Elements',
    'email_activity',
    'formatting',
    'functions',
    'functions_reference',
    'g_form',
    'global',
    'GlideAdministrationMenu',
    'GlideAggregate',
    'GlideAjax',
    'GlideBox',
    'GlideClientCache',
    'GlideContextMenu',
    'GlideDate',
    'GlideDateTime',
    'GlideDecoration',
    'GlideDialogForm',
    'GlideDialogWindow',
    'GlideDraggable',
    'GlideDuration',
    'GlideEncodedQuery',
    'GlideEventHandler',
    'GlideFilter',
    'GlideForm',
    'GlideList',
    'GlideList2',
    'GlideListAggregates',
    'GlideListRecord',
    'GlideMenu',
    'GlidePane',
    'GlidePaneForm',
    'GlideRecord',
    'GlideSession',
    'GlideSortSpec',
    'GlideSystem',
    'GlideTabs2',
    'GlideURL',
    'GlideUser',
    'GlideViewManager',
    'GlideWindow',
    'GWT',
    'list_filter',
    'MultipleUpdate',
    'NameMapEntry',
    'onchange',
    'PartialPage',
    'popupdivs',
    'popups',
    'rico_effect',
    'scrollable',
    'Select',
    'ServiceCatalogForm',
    'slushbucket',
    'SlushBucket_class',
    'sn_ws',
    'spell',
    'StackManagement',
    'StopWatch',
    'sys_report_condition',
    'Table',
    'TableExtension',
    'TemplateRecord',
    'User',
    'utils',
]

// Client list thanks to:
// https://docs.servicenow.com/bundle/newyork-servicenow-platform/page/build/service-portal/reference/client-script-reference.html
// https://developer.servicenow.com/app.do#!/api_doc?v=newyork&id=client
// https://snprotips.com/undocumented-servicenow-apis#client-side-apis
// https://www.servicenowguru.com/
// ... and manually combing through the raw script source, by yours truly
const clientGlobalList = [
    'CustomEvent',
    'DynamicTranslation',
    'GlideAjax',
    'GlideDialogForm',
    'GlideDialogWindow',
    'GlideFlow',
    'GlideModalForm',
    'GlideRecord',
    'GlideUI',
    'GwtContextMenu',
    'GwtMessage',
    'NOW',
    'NotifyOnTaskClient',
    'SNC',
    'ScriptLoader',
    'Table',
    'g_aw',
    'g_form',
    'g_item',
    'g_list',
    'g_menu',
    'g_navigation',
    'g_scratchpad',
    'g_service_catalog',
    'g_tabs2List',
    'g_tabs2Sections',
    'g_ui_scripts',
    'g_user',
    'g_user_date_format',
    'g_user_date_time_format',
    'getDateFromFormat',
    'getMessage',
    'getNavWindow',
    'getUIScript',
    'nowapi',
    'openFrameAPI',
    'spAriaUtil',
    'spContextManager',
    'spModal',
    'spUtil',
]

export const serverGlobals = objectify(serverGlobalList)
export const clientGlobals = objectify(clientGlobalList)
